config/routes.rb
Kerbalsite::Application.routes.draw do
  devise_for :accounts, path: 'auth'

  resources :accounts

  resources :mods, except: [:index] do
    member do
      get :download
      get :subscribe
      get :like
      get :dislike
    end
  end

  get 'mods', to: 'mods#index', mod_type: 'plugin'
  get 'crafts', to: 'mods#index', mod_type: 'craft'
  get 'parts', to: 'mods#index', mod_type: 'part'

  resources :pages, path: '/', only: [] do
    collection do
      get :home
      get :contact
      get :faq
      get :search
    end
  end

  namespace :api, path: '/', constraints: { subdomain: 'api' } do
  end

  root to: 'pages#home'
end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :database_authenticatable, :authentication_keys => [ :username ]
  devise :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mods, dependent: :destroy

  has_and_belongs_to_many :subscribed_mods, class_name: 'Mod'

  acts_as_voter

  validates :username, presence: true,
  					   length: { in: 5..25 },
  					   uniqueness: true

  validates :first_name, presence: true,
  					     length: { in: 1..50 }
  validates :last_name, presence: true,
  					     length: { in: 1..50 }

  validates :country, presence: true

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def mailboxer_email(object)
    (Rails.env == 'development') ? nil : email
  end

  def gravatar_url
    gravatar_id = Digest::MD5.hexdigest(self.email.downcase)
    "http://www.gravatar.com/avatar/#{gravatar_id}?s=100"
  end
end

app/models/mod.rb
class Mod < ActiveRecord::Base
  CONTENT_ALLOWED_IMAGE = Settings.file_upload.allowed.image
  CONTENT_ALLOWED_ARCHIVE = Settings.file_upload.allowed.archive

  belongs_to :account
  has_and_belongs_to_many :subscribed_accounts, class_name: 'Account'

  enum mod_type: [ :plugin, :part, :craft ]

  acts_as_votable # Likes / Dislikes
  acts_as_taggable

  # Paperclip
  has_attached_file :thumbnail, styles: { thumb: '320x150#' }
  has_attached_file :banner, styles: { medium: '800x300#' }
  has_attached_file :mod

  searchkick # Search Engine

  after_thumbnail_post_process :rename_thumbnail
  after_banner_post_process :rename_banner

  before_save :rename_mod_file

  # Validations

  ## Thumbnail
  validates_attachment_presence :thumbnail
  validates_attachment_content_type :thumbnail, :message => 'is an invalid image format. Accepted formats: ' + CONTENT_ALLOWED_IMAGE.to_s, :content_type => CONTENT_ALLOWED_IMAGE

  ## Banner
  validates_attachment_presence :banner
  validates_attachment_content_type :banner, :message => 'is an invalid image format. Accepted formats: ' + CONTENT_ALLOWED_IMAGE.to_s, :content_type => CONTENT_ALLOWED_IMAGE

  ## Mod File
  validates_attachment_presence :mod
  validates_attachment_content_type :mod, :message => 'is an invalid archive format. Accepted formats: ' + CONTENT_ALLOWED_ARCHIVE.to_s, :content_type => CONTENT_ALLOWED_ARCHIVE
  validates_attachment_size :mod, :less_than => 200.megabytes

  # Validations

	validates :name, presence: true, length: { in: 1..30 }
	validates :description, presence: true, length: { in: 1..3000 }
  validates :description_short, presence: true, length: { in: 1..100 }
	validates :version, presence: true

  validates :youtube_url, presence: true, url: true

  def vote_tally
    self.likes.size - self.dislikes.size
  end

  private
  def rename_thumbnail
    extension = File.extname(thumbnail_file_name).downcase
    self.thumbnail.instance_write :file_name, "#{Time.now.to_i.to_s}#{extension}"

  end

  def rename_banner
    extension = File.extname(banner_file_name).downcase
    self.banner.instance_write :file_name, "#{(Time.now.to_i + 1).to_s}#{extension}"
  end

  def rename_mod_file
    name = File.basename(mod_file_name).downcase
    extension = File.extname(mod_file_name).downcase
    self.mod.instance_write :file_name, "#{Time.now.to_i.to_s}_#{name}#{extension}"
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def show
		@user = Account.find(params[:id])
	end

	private
	def account_params
		params.require(:account).permit(:username, :first_name, :last_name, :country)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

  utf8_enforcer_workaround

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :first_name, :last_name, :country) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :first_name, :last_name, :country) }
	end
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  before_filter :require_permission, only: [:edit, :update, :destroy]
	before_action :authenticate_account!, except: [:index, :show]

	def index
    if params.has_key?(:tag)
      mods = Mod.tagged_with(params[:tag])

      @tag = params[:tag]
      @mods = mods.paginate(:page => params[:page], :per_page => 15)
    elsif params.has_key?(:search)
      @mods = Mod.search params[:search], fields: [:name], page: params[:page], per_page: 15
    else
      @mods = Mod.paginate(:page => params[:page], :per_page => 15)
    end
	end

	def show
		@mod = Mod.find(params[:id])
	end

	def new
		@mod = Mod.new
	end

	def create
		@mod = Mod.new(mod_params)
    @mod.account = current_account

		if @mod.save
			redirect_to @mod, flash: { success: 'Mod was successfully created.' }
		else
			render 'new'
		end
	end

	def edit
    @mod = Mod.find(params[:id])
	end

	def update
    @mod = Mod.find(params[:id])

    if @mod.update_attributes(mod_params)
      redirect_to @mod, flash: { success: 'Mod successfully updated.' }
    else
      flash[:danger] = 'Error updating mod!'
      render 'edit'
    end
  end

  def destroy
    @mod = Mod.find(params[:id])

    @mod.destroy

    redirect_to mods_path, flash: { success: 'Mod was successfully deleted. '}
  end

	def subscribe
    @mod = Mod.find(params[:id])

    if !current_account.subscribed_mods.include? @mod
      @mod.subscribed_accounts << current_account
      flash_message = "You have subscribed to #{@mod.name}."
    else
      @mod.subscribed_accounts.delete current_account
      current_account.subscribed_mods.delete @mod

      current_account.save

      flash_message = "You have unsubscribed from #{@mod.name}."
    end

    @mod.save

    redirect_to @mod, flash: { success: flash_message }
	end

	def download
    @mod = Mod.find(params[:id])

    redirect_to @mod.mod.url

    @mod.increment(:download_count).save
  end

  def like
    mod = Mod.find(params[:id])

    if current_account.voted_up_on? mod
      mod.unliked_by current_account
    else
      mod.liked_by current_account
    end

    redirect_to mod
  end

  def dislike
    mod = Mod.find(params[:id])

    if current_account.voted_down_on? mod
      mod.undisliked_by current_account
    else
      mod.disliked_by current_account
    end

    redirect_to mod
  end

	private
	def mod_params
		params.require(:mod).permit(:name, :description, :description_short, :version, :tag_list, :download_count, :thumbnail, :banner, :youtube_url, :mod)
  end

  def require_permission
    if current_account != Mod.find(params[:id]).account
      redirect_to current_account, flash: { danger: 'You do not own that mod!' }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def search
  end

  def faq
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cp(path)
		'active' if current_page?(path)
	end	
	
	def site_title(given)
		(given.nil? || given.blank?) ? Settings.general.site_title : (given + ' - ' + Settings.general.site_title_short)
	end

	def better_flash(type)
		switched = { 'notice' => 'success', 'alert' => 'danger' }

		if switched.key?(type)
			switched[type]
		else
			type
		end
  end

  def nice_date(date)
    date.strftime('%B') + ' ' + date.strftime('%e').to_i.ordinalize + ' ' + date.strftime('%Y')
  end
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/_mods.html.erb
<h2></h2>

<% if !account.mods.empty? %>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
        <tr>
          <th>Name</th>
          <th>Downloads</th>
          <th>Likes</th>
        </tr>
    </thead>
    <tbody id="items">
        <% account.mods.each do |mod| %>
            <tr>
              <td><%= link_to mod.name, mod %></td>
              <td><%= mod.download_count %></td>
              <td><%= mod.vote_tally %></td>
              <% if account == mod.account %>
                  <td>
                    <%= link_to 'Edit', edit_mod_path, class: 'btn btn-sm btn-warning' %>
                    <%= link_to 'Delete', mod, class: 'btn btn-sm btn-danger', method: :delete %>
                  </td>
              <% end %>
            </tr>
        <% end %>
    </tbody>
  </table>
</div>
<% else %>
<h2><i>You do not have any mods.</i></h2>
<% end %>

app/views/accounts/_settings.html.erb
<hr>
<form class="form" action="##" method="post" id="registrationForm">
  <div class="form-group">

    <div class="col-xs-6">
      <label for="first_name"><h4>First name</h4></label>
      <input type="text" class="form-control" name="first_name" id="first_name" placeholder="first name" title="enter your first name if any.">
    </div>
  </div>
  <div class="form-group">

    <div class="col-xs-6">
      <label for="last_name"><h4>Last name</h4></label>
      <input type="text" class="form-control" name="last_name" id="last_name" placeholder="last name" title="enter your last name if any.">
    </div>
  </div>

  <div class="form-group">

    <div class="col-xs-6">
      <label for="phone"><h4>Phone</h4></label>
      <input type="text" class="form-control" name="phone" id="phone" placeholder="enter phone" title="enter your phone number if any.">
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-6">
      <label for="mobile"><h4>Mobile</h4></label>
      <input type="text" class="form-control" name="mobile" id="mobile" placeholder="enter mobile number" title="enter your mobile number if any.">
    </div>
  </div>
  <div class="form-group">

    <div class="col-xs-6">
      <label for="email"><h4>Email</h4></label>
      <input type="email" class="form-control" name="email" id="email" placeholder="you@email.com" title="enter your email.">
    </div>
  </div>
  <div class="form-group">

    <div class="col-xs-6">
      <label for="email"><h4>Location</h4></label>
      <input type="email" class="form-control" id="location" placeholder="somewhere" title="enter a location">
    </div>
  </div>
  <div class="form-group">

    <div class="col-xs-6">
      <label for="password"><h4>Password</h4></label>
      <input type="password" class="form-control" name="password" id="password" placeholder="password" title="enter your password.">
    </div>
  </div>
  <div class="form-group">

    <div class="col-xs-6">
      <label for="password2"><h4>Verify</h4></label>
      <input type="password" class="form-control" name="password2" id="password2" placeholder="password2" title="enter your password2.">
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <br>
      <button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Save
      </button>
      <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>
    </div>
  </div>
</form>

app/views/accounts/_subscribed.html.erb
<h2></h2>

<% if !account.subscribed_mods.empty? %>
    <div class="table-responsive">
      <table class="mods borderless">
        <% account.subscribed_mods.each do |mod| %>
            <tr>
              <td><h4><%= link_to mod.name, mod %></h4></td>
              <% if current_account == account %>
                  <td>
                    <div class="pull-right">
                      <%= link_to 'Unsubscribe', subscribe_mod_path(mod), class: 'btn btn-danger action-button' %>
                    </div>
                  </td>
              <% end %>
            </tr>
        <% end %>
      </table>
    </div>
<% else %>
    <h2><i>You are not subscribed to any mods.</i></h2>
<% end %>

app/views/accounts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10"><h1><%= @user.username %></h1></div>
    <div class="col-sm-2">
    <span class="pull-right">
      <img title="profile image" class="img-circle img-responsive" src="<%= @user.gravatar_url %>">
    </span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">

      <ul class="list-group">
        <li class="list-group-item text-muted">Profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Name</strong></span> <%= @user.full_name %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Country</strong></span> <%= @user.country %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> <%= nice_date @user.last_sign_in_at %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> <%= nice_date @user.created_at %></li>

      </ul>

      <ul class="list-group">
        <li class="list-group-item text-muted">Activity</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Mods</strong></span> <%= @user.mods.count %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> <%= @user.find_liked_items.count %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Dislikes</strong></span> <%= @user.find_disliked_items.count %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Subscribed</strong></span> 0</li>
      </ul>

      <div class="panel panel-default">
        <div class="panel-heading">Social Media</div>
        <div class="panel-body">
          <i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i>
          <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
        </div>
      </div>

      <% if current_account == @user %>
          <hr />

          <div align="center">
            <%= link_to 'Update Profile', edit_account_registration_path, class: 'btn btn-primary' %>
          </div>
      <% end %>

    </div>
    <div class="col-sm-9">

      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
        <li><a href="#mods" data-toggle="tab">My Mods</a></li>
        <li><a href="#subscribed" data-toggle="tab">Subscribed</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="home">
            <h1>Welcome Home</h1>
        </div>

        <div class="tab-pane" id="mods">
            <%= render partial: 'mods', locals: { account: @user } %>
        </div>

        <div class="tab-pane" id="subscribed">
            <%= render partial: 'subscribed', locals: { account: @user } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_flash.html.erb
<div class="flash">
  <% flash.each do |type, message| -%>
      <% type = better_flash type %>
      <div class="alert alert-dismissable alert-<%= type %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p><%= message %></p>
      </div>
  <% end -%>
</div>

app/views/application/_footer.html.erb
<footer style="padding-top: 0px;"></footer>

app/views/application/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= Settings.general.site_title %></a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= cp(root_path) %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= cp(mods_path) %>"><%= link_to 'Mods', mods_path %></li>
        <li class="<%= cp('') %>"><%= link_to 'Crafts', '' %></li>
        <li class="<%= cp('') %>"><%= link_to 'Parts', '' %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= render partial: 'header_search' %>
        <%= render partial: 'header_authentication' %>
      </ul>

    </div>
  </div>
</div>

app/views/application/_header_authentication.html.erb
<% if !account_signed_in? %>
    <li class="<%= cp(new_account_session_path) %>"><%= link_to 'Sign In', new_account_session_path %></li>
	<li class="<%= cp(new_account_registration_path) %>"><%= link_to 'Sign Up', new_account_registration_path %></li>
<% else %>
    <li class="<%= cp(new_mod_path) %>"><%= link_to 'Upload', new_mod_path %></li>
    <li class="<%= cp(current_account) %>"><%= link_to 'Profile', current_account %></li>
	<li><%= link_to 'Sign Out', destroy_account_session_path, method: :delete %></li>
<% end %>

app/views/application/_header_search.html.erb
<li>
	<%= form_tag mods_path, method: 'get', class: 'navbar-form navbar-right', style: 'margin-right: 2px;' do %>
		<%= text_field_tag :search, params[:search], class: 'form-control col-lg-8', placeholder: 'Search' %>
	<% end %>
</li>

app/views/application/_metadata.html.erb
<%= csrf_meta_tags %>

app/views/application/_scripts.html.erb
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

app/views/application/_styles.html.erb
<%= stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css' %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= site_title(yield :title)  %></title>
		
		<%= render partial: 'styles' %>
		<%= render partial: 'metadata' %>
	</head>

	<body>
		<div class="wrap">
			<%= render partial: 'header' %>

			<div id="main-container" class="container">
				<%= render partial: 'flash' %>
				<%= yield %>
			</div> 
			<div id="push"></div>
		</div>

		<%= render partial: 'footer' %>
		<%= render partial: 'scripts' %>
	</body>
</html>

app/views/mods/_box.html.erb
<% if homepage
     divClass = 'col-lg-3 col-md-6'
   else
     divClass = 'acol-sm-4 col-lg-4 col-md-4'
   end
%>

<div class="<%= divClass %>">
  <div class="thumbnail">
    <%= image_tag mod.thumbnail.url(:thumb) %>

    <div class="caption">
      <h4 width="75%" style="text-overflow: ellipsis;"><%= link_to mod.name, mod %></h4>

      <span class="game-version label label-info pull-right"><%= mod.version %></span>
      <p><%= mod.description_short %></p>
    </div>

    <div class="ratings">
      <p class="pull-right"><%= mod.download_count %> downloads</p>
      <p>
        <%= mod.vote_tally %> likes
      </p>
    </div>
  </div>
</div>

app/views/mods/_form.html.erb
<div class="block-form">
    <h2>Upload New Mod</h2>
    <hr/>

  <% if @mod.errors.full_messages.any? %>
      <% @mod.errors.delete(:mod_file) %>
      <% @mod.errors.delete(:image) %>
      <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h4><%= @mod.errors.full_messages.count %> errors prevented this form from being registered:</h4>
        <ul>
          <% @mod.errors.full_messages.each do |error_message| %>
              <li><h5><%= error_message %></h5></li>
          <% end %>
        </ul>
      </div>
  <% end %>

    <div class="well">
      <%= form_for @mod, html: { class: 'form-horizontal '} do |f| %>
          <fieldset>
            <legend>Details</legend>
            <div class="form-group">
              <div class="col-lg-12">
                <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Name' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-12">
                <%= f.text_field :description_short, class: 'form-control input-lg', placeholder: 'Short Description' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-12">
                <%= f.text_area :description, class: 'form-control input-lg', placeholder: 'Description' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-12">
                <%= f.select :version, ['0.21.0', '0', '0'], { prompt: 'KSP Version' }, { class: 'form-control input-lg' }%>
              </div>
            </div>
          </fieldset>

          <fieldset>
            <legend>Mod</legend>
            <div class="form-group">
              <div class="col-lg-12">
                <%= f.file_field :mod, class: 'form-control input-lg' %>
              </div>
            </div>
          </fieldset>

          <fieldset>
            <legend>Images</legend>
            <div class="form-group">
              <label class="col-lg-2 control-label">Thumbnail (320x150)</label>
              <div class="col-lg-10">
                <%= f.file_field :thumbnail, class: 'form-control input-lg' %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Banner (800x300)</label>
              <div class="col-lg-10">
                <%= f.file_field :banner, class: 'form-control input-lg' %>
              </div>
            </div>
          </fieldset>

          <fieldset>
            <legend>Social</legend>
            <div class="form-group">
              <div class="col-lg-12">
                <%= f.text_field :tag_list, class: 'form-control input-lg', id: 'mod-tags', placeholder: 'Tags' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-12">
                <%= f.text_field :youtube_url, class: 'form-control input-lg', placeholder: 'YouTube Video Link' %>
              </div>
            </div>

          </fieldset>

          <fieldset>
            <div class="form-group">
              <div class="col-lg-12">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Upload Mod</button>
              </div>
            </div>
          </fieldset>
        <% end %>
    </div>
</div>

app/views/mods/edit.html.erb
<%= render partial: 'form' %>

app/views/mods/index.html.erb
<div class="row">

  <div class="col-md-3">
    <p class="lead">Mods</p>
    <div class="list-group">
      <a href="#" class="list-group-item">Category #1</a>
      <a href="#" class="list-group-item">Category #2</a>
      <a href="#" class="list-group-item">Category #3</a>
    </div>
  </div>

  <div class="col-md-9">

    <div class="row">
      <% if @mods.empty? %>
          <div align="center">
              <% tag_message = (@tag.nil?) ? '' : ' with the tag \'' + @tag + '\'' %>
              <h3>No mods found<%= tag_message %>.</h3>
              <h3 style="padding-top: 30px;"><%= link_to 'Upload a Mod', new_mod_path, class: 'btn btn-default btn-lg' %></h3>
          </div>
      <% end %>
      <% @mods.each do |mod| %>
        <%= render partial: 'box', locals: { mod: mod, homepage: false } %>
      <% end %>
    </div>
    <div align="center">
        <%= will_paginate @mods, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/mods/new.html.erb
<%= render partial: 'form' %>

app/views/mods/show.html.erb
<div class="row">

  <div class="col-md-3">

    <div class="btn-group btn-group-justified">


      <%= link_to 'Download', download_mod_path, class: 'btn btn-lg btn-primary' %>
      <% if account_signed_in? %>
          <%
             subscribed = (!current_account.subscribed_mods.include? @mod)

             subscribe_text = (subscribed) ? 'Subscribe' : 'Unsubscribe'
             subscribe_class = (subscribed) ? 'success' : 'danger'
          %>
          <%= link_to subscribe_text, subscribe_mod_path, class: 'btn btn-lg btn-' + subscribe_class %>
      <% end %>
    </div>

    <br/>
    <% if account_signed_in? %>
        <div align="center"><i><%= link_to 'Whats the difference?', faq_pages_path %></i></div>
    <% end %>

    <% if current_account == @mod.account %>
        <br/>
        <hr/>
        <div class="btn-group btn-group-justified">
          <%= link_to 'Edit', edit_mod_path, class: 'btn btn-warning btn-lg' %>
          <%= link_to 'Destroy', @mod, class: 'btn btn-danger btn-lg', method: :delete %>
        </div>
    <% end %>


  </div>

  <div class="col-md-9">

    <div class="thumbnail">
      <%= image_tag @mod.banner.url(:medium) %>
      <div class="caption-full">
        <div class="pull-right">
          <%= link_to 'YouTube', @mod.youtube_url, class: 'label label-primary', style: 'font-size: 15px;' %>
          <span class="game-version label label-info" style="font-size: 15px"><%= @mod.version %></span>
        </div>
        <h4><%= @mod.name %></h4>
        <hr />
        <%= @mod.description %>

      </div>
      <div class="ratings">
        <p class="pull-right">
          <%= @mod.download_count %> downloads<br/>
          <%= @mod.vote_tally %> likes
        </p>

        <%
           if account_signed_in?
             like_class = (current_account.voted_up_on? @mod) ? 'success' : 'default'
             dislike_class = (current_account.voted_down_on? @mod) ? 'danger' : 'default'
           else
             like_class = 'primary'
             dislike_class = 'primary'
           end
        %>
        <% if account_signed_in? %>
            <p>
              <span class="label label-default"></span>
              <%= link_to fa_icon('thumbs-up'), like_mod_path, class: 'btn btn-sm btn-' + like_class %>
              <%= link_to fa_icon('thumbs-down'), dislike_mod_path, class: 'btn btn-sm btn-' + dislike_class %>
            </p>
        <% else %>
            <br />
        <% end %>

        <p>
          <span class="label label-info"><%= link_to @mod.mod_type.humanize, crafts_path, class: 'tag-link' %></span>
          <% @mod.tags.each do |tag| %>
              <span class="label label-default"><%= link_to tag, mods_path(tag: tag.to_s), class: 'tag-link' %></span>
          <% end %>
        </p>


      </div>
    </div>

    <div class="well">
      <div id="disqus_thread"></div>
      <script type="text/javascript">
          var disqus_shortname = 'kerbalmods';

          /* * * DON'T EDIT BELOW THIS LINE * * */
          (function () {
              var dsq = document.createElement('script');
              dsq.type = 'text/javascript';
              dsq.async = true;
              dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
      </script>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Frequently Asked Questions</h1>

app/views/pages/home.html.erb
<% content_for :title, '' %>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://placehold.it/1200x500" alt="">
    </div>
    <div class="item">
      <img src="http://placehold.it/1200x500" alt="">
    </div>
    <div class="item">
      <img src="http://placehold.it/1200x500" alt="">
    </div>
  </div>
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<hr>

<div class="row">
  <div class="col-lg-12">
    <h3>Top Rated Mods</h3>
  </div>
</div>

<% top_mods = Mod.all.sort_by { |mod| mod.vote_tally } %>

<div class="row">

  <% top_mods.each do |mod| %>
      <%= render partial: 'mods/box', locals: { mod: mod, homepage: true } %>
  <% end %>
</div>